name: Docker Image CD

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout out the codebase
      uses: actions/checkout@v3
      
    - name: Build the Docker image
      run: docker build . -t agnes-rutkowska/continuous-serve-image
